### ISSUE TITLE
Tests fail with ruby 2.2

### ISSUE THREAD

**Issue by graaff** [svenfuchs/test_declarative#5]
With ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux] I'm seeing the following test failure:

```
Error: test_adds_a_test_method(TestDeclarativeTest)
: NameError: uninitialized constant TestDeclarativeTest::MiniTest
test/test_declarative_test.rb:14:in `test_adds_a_test_method'
     11:   def test_adds_a_test_method
     12:     called = false
     13:     assert_nothing_raised { Test::Unit::TestCase.test('some test') { called = true } }
  => 14:     Test::Unit::TestCase.new(:'test_some_test').run((RUBY_VERSION < '1.9.1' ? Test::Unit::TestResult : MiniTest::Unit).new) {}
     15:     assert called
     16:   end
     17: end
```

I'm running "ruby test/test_declarative_test.rb" to get this. I've played around a little bit with this, but adding something like "require 'minitest/unit'" only leads to errors related to add_error later on. These seem to be confusing TestUnit and MiniTest test units. It's not clear to me if the problem is with the test or with the code itself.

**Comment by junaruga** [comment]
Hello @graaff 
Sorry for late replying.
Thank you for reporting the issue.

> something like "require 'minitest/unit'" only leads to errors related to add_error later on. These seem to be confusing TestUnit and MiniTest test units.

It looks so.

I improved the test.
https://github.com/svenfuchs/test_declarative/blob/master/test/test_declarative_test.rb

I guess that I could fix your issue, though I did not still pass the unit test for the case to use the latest `unit-test` gem.
https://travis-ci.org/svenfuchs/test_declarative

**Comment by graaff** [comment]
I can confirm that this fixes both minitest cases (Gemfile and Gemfile.minitest4). I'm also seeing the error with Gemfile.unit-test but that appears to be unrelated to this issue.

**Comment by junaruga** [comment]
@graaff Thank you for the checking. Yeah, I have to fix the error with `Gemfile.unit-test`.
So, I would close this page for the issue of `minitest`.
